apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
  labels:
  {{- range $key,$val := .Values.service.labels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
spec:
  {{- if eq .Values.service.headless true }}
  clusterIP: None
  {{- end}}
  ports:
  {{- range .Values.service.ports }}
  - port: {{ .port }}
    name: {{ .name }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
  {{- end }}
  selector:
    name: {{ .Release.Name }}
