# Default values for MY_CHART.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global:
  image:
    # -- Default registry for all control plane Images
    registry: "mvatandoost"
    # -- The default tag for all images, which itself defaults to .Chart.AppVersion
    tag: 886210
    pullPolicy: IfNotPresent
  # -- Add `imagePullSecrets` to all the service accounts used for control-plane components
  imagePullSecrets: [name: registry-secret, name: mvatandoost]
  

controlPlane:
  imageName: "control-plane"


# imagePullSecrets: [name: registry-secret, name: mvatandoost]
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

service:
  labels:
    monitoring-app: xds-apps
  type: clusterIP
  headless: true
  ports:
  - name: grpc
    port: 8888
    targetPort: 8888
    protocol: TCP
  - name: api
    port: 8080
    targetPort: 8080
    protocol: TCP  
  - name: metrics
    port: 9000
    targetPort: 9000
    protocol: TCP


resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi

configMap:
  data:
    METRIC_LISTENPORT: 9000
    LOGGER_LEVEL: "info"
    XDS_PORT: 8888
    GRPC_TIMEOUT: 5
    REST_API_HTTP_PORT: 8080

