# Default values for MY_CHART.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mvatandoost/xds-grpc-client-example
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: [name: registry-secret, name: mvatandoost]
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

service:
  labels:
    monitoring-app: xds-apps
    xds: active
  type: clusterIP
  headless: true
  ports:
  - name: metrics
    port: 9000
    targetPort: 9000
    protocol: TCP


resources:
  limits:
    cpu: 800m
    memory: 9000Mi
  requests:
    cpu: 200m
    memory: 500Mi

configMap:
  data:
    METRIC_LISTENPORT: 9000
    LOGGER_LEVEL: "error"
    Server1Address: "xds-grpc-server-example-headless:8888"
