# Default values for MY_CHART.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global:
  image:
    # -- Default registry for all control plane Images
    registry: "mvatandoost"
    # -- The default tag for all Kuma images, which itself defaults to .Chart.AppVersion
    tag: 886210
    pullPolicy: IfNotPresent
  # -- Add `imagePullSecrets` to all the service accounts used for Kuma components
  imagePullSecrets: [name: registry-secret, name: mvatandoost]

clientExample:
  imageName: "cp-example-client"


imagePullSecrets: [name: registry-secret, name: mvatandoost]


nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

service:
  labels:
    monitoring-app: xds-apps
    xds: active
  type: clusterIP
  headless: true
  ports:
  - name: metrics
    port: 9000
    targetPort: 9000
    protocol: TCP


resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 200m
    memory: 100Mi

configMap:
  data:
    METRIC_LISTENPORT: 9000
    LOGGER_LEVEL: "info"
    GRPC_GO_LOG_VERBOSITY_LEVEL: 99
    GRPC_GO_LOG_SEVERITY_LEVEL: "info"
    Server1Address: "xds:///xds-grpc-server-example-headless.control-plane-example:8888"
    GRPC_XDS_BOOTSTRAP: "./xds_bootstrap.json"
    # GRPC_XDS_BOOTSTRAP_CONFIG: "{\n  \"xds_servers\": [\n    {\n      \"server_uri\": \"xds-control-plane-headless.xds-control-plane.svc.cluster.local:8888\",\n      \"channel_creds\": [\n        {\n          \"type\": \"insecure\"\n        }\n      ],\n      \"server_features\": [\"xds_v3\"]      \n    }\n  ],\n  \"node\": {\n    \"id\": \"b7f9c818-fb46-43ca-8662-d3bdbcf7ec18~10.0.0.1\",\n    \"metadata\": {\n      \"R_GCP_PROJECT_NUMBER\": \"123456789012\"\n    },\n    \"locality\": {\n      \"zone\": \"us-central1-a\"\n    }\n  }\n}\n"

