# Default values for MY_CHART.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: mvatandoost/xds-grpc-server-example
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: [name: registry-secret, name: mvatandoost]
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

service:
  labels:
    monitoring-app: xds-apps
    xds: active
  type: clusterIP
  headless: true
  ports:
  - name: grpc
    port: 8888
    targetPort: 8888
    protocol: TCP
  - name: metrics
    port: 9000
    targetPort: 9000
    protocol: TCP


resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 200m
    memory: 100Mi

configMap:
  data:
    METRIC_LISTENPORT: 9000
    REST_LISTENPORT: 8080
    LOGGER_LEVEL: "error"
    GRPC_LISTENPORT: 8888
    GRPC_TIMEOUT: 5
