# Default values for MY_CHART.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2


global:
  image:
    # -- Default registry for all control plane Images
    registry: "mvatandoost"
    # -- The default tag for all images, which itself defaults to .Chart.AppVersion
    tag: 886210
    pullPolicy: IfNotPresent
  # -- Add `imagePullSecrets` to all the service accounts used for components
  imagePullSecrets: [name: registry-secret, name: mvatandoost]

serverExample:
  imageName: "cp-example-server"


nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

service:
  labels:
    monitoring-app: xds-apps
    xds/portName: grpc
  type: clusterIP
  headless: true
  ports:
  - name: grpc
    port: 8888
    targetPort: 8888
    protocol: TCP
  - name: metrics
    port: 9000
    targetPort: 9000
    protocol: TCP


resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 200m
    memory: 100Mi

configMap:
  data:
    METRIC_LISTENPORT: 9000
    REST_LISTENPORT: 8080
    LOGGER_LEVEL: "info"
    GRPC_LISTENPORT: 8888
    GRPC_TIMEOUT: 5
    XDS_PORT: 5678
