name: Main

on:
  push:
  workflow_dispatch:

env:
  DOCKER_REPOSITORY_ACCESS_TOKEN: ${{ secrets.DOCKER_REPOSITORY_ACCESS_TOKEN }}
  DOCKER_REPOSITORY_NAME: ${{ vars.DOCKER_REPOSITORY_NAME }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        run: docker login  -u $DOCKER_REPOSITORY_NAME -p $DOCKER_REPOSITORY_ACCESS_TOKEN

      - name: Build Example client
        working-directory: ./example/client
        run: docker build . --tag $DOCKER_REPOSITORY_NAME/xds-grpc-client-example:latest

      - name: Push Example client
        run: docker push $DOCKER_REPOSITORY_NAME/xds-grpc-client-example:latest

